### ISSUE TITLE
Add LinearLayout containers for each to-do instance.

### ISSUE THREAD

**Issue by ZogopZ** [ZogopZ/to-do#15]
- [x] Each to-do instance must be implemented as a horizontal LinearLayout (child to the 'gridLayout' View).
- [x] Each to-do instance must contain a 'clockInstance' along with its removal button and the to-do's actual text.
- [x] to-do instances must be accordingly rearranged when the user adds or updates 'clockInstance' values.
