### ISSUE TITLE
Rework focus when the user initiates to-do instance.

### ISSUE THREAD

**Issue by ZogopZ** [ZogopZ/to-do#20]
- [x] When the user presses add to-do button the focus should jump to the first clock view of the clock instance of the newly initialized to-do instance.
- [x] When the user fills the last clock view, the focus should automatically jump to the to-do EditText view.
- [x] When the user presses IME_ACTION_DONE button on to-do EditText view, the to-do instances should be rearranged according to time ascending.
